# Logistic regression

## Nececary imports

In [1]:
from ipynb.fs.full.Utils import load_dataset, scale_data
import numpy as np
from matplotlib import pyplot as plt

In [2]:
from sklearn import model_selection
from sklearn import preprocessing
from sklearn import metrics
from sklearn import linear_model

## Loading the data

In [3]:
x_train, x_test, y_train, y_test = load_dataset()

In [4]:
print("Train size:\t%5d\nTest size:\t%5d" % (x_train.shape[0], x_test.shape[0]))

Train size:	14457
Test size:	 6196


## Training the model

In [5]:
model = linear_model.LogisticRegression(solver='sag', multi_class='multinomial')
model.fit(x_train, y_train);

/opt/anaconda/lib/python3.6/site-packages/sklearn/linear_model/sag.py:326: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


## Evaluation

In [6]:
y_pred_train = model.predict(x_train)

In [7]:
acc = metrics.accuracy_score(y_train, y_pred_train)
rec = metrics.recall_score(y_train, y_pred_train, average='weighted')
f1 = metrics.f1_score(y_train, y_pred_train, average='weighted')
print('Train accuracy: %g\nRecall:   %g\nF1 score: %g' % (acc, rec, f1))

Train accuracy: 0.328215
Recall:   0.328215
F1 score: 0.294022


/opt/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [11]:
metrics.confusion_matrix(y_train, y_pred_train)

[[1995 1920  113  161    0   45   49  127    4    0   89    2    1    6]
 [1908 2018  112  148    1   43   44  136    4    0   89    2    1    6]
 [ 218  133  181    0    0    1    4    0    0    0    3    0    0    0]
 [ 301  164    0  164    0    2    7    0    1    0    0    0    0    3]
 [ 286  172   42    0    0    5    3    6    0    0   20    0    3    0]
 [ 221  207    7    0    0   43    4    0    0    0    0    0    0    0]
 [ 200  107   26    6    0    2   45    0    1    0    0    0    0    2]
 [ 153  195    1    0    0    0    0  166    0    0    9    0    0    1]
 [ 234  107    6    1    0    0    8    4    8    0    1    0    0    0]
 [  43   25    1    2    0    0    2    0    0    0    0    0    0    0]
 [ 145  178   24    0    0    0    0   29    0    0  117    0    0    0]
 [ 198  117    1   17    0    2    4    0    0    0    0    3    0    0]
 [ 305  238   18    0    0    2    2   32    0    0   22    0    2    0]
 [ 248  119    3   30    0    0    7    3    2    0

In [8]:
y_pred = model.predict(x_test)

In [9]:
acc = metrics.accuracy_score(y_test, y_pred)
rec = metrics.recall_score(y_test, y_pred, average='weighted')
f1 = metrics.f1_score(y_test, y_pred, average='weighted')
print('Accuracy: %g\nRecall:   %g\nF1 score: %g' % (acc, rec, f1))

Accuracy: 0.301646
Recall:   0.301646
F1 score: 0.271124


/opt/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
